language: go
sudo: false
install:
- go get github.com/smartystreets/goconvey/convey
- go get github.com/willf/bitset
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
notifications:
  email: false
go:
- 1.4
- 1.5
- 1.6
- tip

matrix:
  allow_failures:
  - go: tip

dd:
  secure: blcYYnnNVC5tFjDb74FUyvyYln5gzbBoCPs0AVl3lBjpgd4yH3DYU87lZoPimzxmDeO4K5Umpw7WBb58rkkpNsdqdIFLVjTWvzw6W56PqKMFGnw1Ux7s3c0A+38j90ied14KqZHnhyNNqmY9Jc6Fc9tHNTcuMT1i3vsDnw6TlfM=
